<a href="https://colab.research.google.com/github/cwood1967/Data_Science_Course/blob/cjw/Intro/numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# importing numpy, with name np by convention

import numpy as np

In [5]:
x_list = [4,1,4,3,5,6]
x = np.array(x_list)

In [6]:
### the numpy array has a fixed length of a static type

type(x), x.shape, x.dtype

(numpy.ndarray, (6,), dtype('int64'))

In [7]:
x[0], x[2]

(4, 4)

In [9]:
x[1] = 3
x[2] = 5.6  # because the array is int64, will be truncated
x

array([4, 3, 5, 3, 5, 6])

In [10]:
#numpy array support vectorized operations

# multiply every element by 2
y = x * 2
y


array([ 8,  6, 10,  6, 10, 12])

In [11]:
'''
math operations element-wise
need the dimensions to be the same
'''
u1 = x * y
u2 = x / y
u2

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [12]:
'''
math function on the array
exp, sqrt, log, trig functions, ...
'''

sy = np.exp(-.1*y)
sy

array([0.44932896, 0.54881164, 0.36787944, 0.54881164, 0.36787944,
       0.30119421])

In [13]:
'''
multi-dimensional arrays
use np.random to generate arrays from a distribution
'''
rx = np.random.randint(0, 10,(100,8)) # 100 rows, 8 columns
rx.shape, rx.dtype

((100, 8), dtype('int64'))

In [14]:
# select only part of the array
# just the first row
rx[0,:]

array([3, 5, 4, 0, 0, 0, 0, 8])

In [15]:
# the first column
rx[:,0]

array([3, 5, 3, 2, 2, 6, 1, 4, 8, 4, 0, 2, 4, 5, 7, 8, 2, 1, 1, 3, 6, 6,
       7, 1, 6, 7, 0, 3, 7, 8, 7, 7, 4, 6, 6, 2, 4, 1, 2, 4, 0, 3, 1, 3,
       7, 3, 9, 6, 6, 4, 1, 0, 8, 2, 5, 0, 8, 5, 9, 1, 1, 9, 0, 0, 6, 2,
       6, 9, 9, 6, 5, 7, 9, 5, 4, 4, 9, 9, 7, 0, 5, 9, 8, 5, 8, 4, 7, 2,
       2, 6, 8, 5, 5, 4, 9, 7, 8, 4, 6, 9])

In [16]:
# a slice from anywhere

rx[13:16, 4:7]   #does not include 16th row or 7th column

array([[9, 6, 9],
       [2, 7, 7],
       [6, 1, 3]])

In [ ]:
'''
all of the slicing operations create a view into the array, not a copy
so be careful if you go changing things
'''
print(rx[0, :])
u = rx[0,:]  ## first row
u[3] = 40
print(u)
print(rx[0,:])

[9 5 1 0 4 6 6 9]
[ 9  5  1 40  4  6  6  9]
[ 9  5  1 40  4  6  6  9]


In [17]:
# use the array method copy to get a copy
print(rx[0, :])
u = rx[0,:].copy()  ## first row
u[2] = 40
print(u)
print(rx[0,:])

[3 5 4 0 0 0 0 8]
[ 3  5 40  0  0  0  0  8]
[3 5 4 0 0 0 0 8]


In [29]:
# use random again for a normal distribution (also see np.random.normal)
rx = np.random.randn(100,8)  # 100 columns, 8 rows
rx.shape, rx.dtype
np.set_printoptions(precision=4, linewidth=100)

In [33]:
# statistics for the entire array
(rx.mean(), rx.std(), rx.min(), rx.max())

(0.010890316769035839, 0.975290381035699, -3.25800571234229, 2.65665796850222)

In [46]:
print(rx.mean(axis=0))
print(rx.std(axis=0))
print(rx.min(axis=0))
print(rx.max(axis=0))

[ 0.1286 -0.0081  0.0376 -0.0494  0.0017 -0.062   0.1096 -0.0709]
[0.9914 0.9334 0.9734 0.9288 0.8931 1.0354 1.0469 0.9691]
[-2.0096 -1.9024 -2.6431 -2.1515 -3.258  -2.6363 -2.5014 -2.0154]
[2.6567 2.2692 2.2453 2.0357 2.5812 1.9627 2.3172 1.9898]


In [ ]:
rx.std(axis=0)

array([0.9691, 0.8408, 1.0019, 1.0117, 1.0919, 0.9961, 0.9523, 0.9431])

In [ ]:
rx.min(axis=0)

array([-2.2278, -1.6038, -2.2911, -2.5581, -3.0908, -2.3611, -2.3539, -2.6386])

In [ ]:
rx.max(axis=0)

array([2.304 , 1.938 , 2.2609, 2.6116, 1.9647, 2.5507, 2.2089, 2.2931])

In [ ]:
### pass functions/methods around like variables
funcs = [np.mean, np.std, np.min, np.max]  #list of functions
for f in funcs:
    print(f.__name__, f(rx, axis=0))

mean [-0.0795  0.1594  0.0175 -0.1353 -0.0811  0.1686  0.0605 -0.0252]
std [0.9691 0.8408 1.0019 1.0117 1.0919 0.9961 0.9523 0.9431]
amin [-2.2278 -1.6038 -2.2911 -2.5581 -3.0908 -2.3611 -2.3539 -2.6386]
amax [2.304  1.938  2.2609 2.6116 1.9647 2.5507 2.2089 2.2931]


In [ ]:
x1 = np.arange(-4,4, .5)
x1, x1.shape

(array([-4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,
         3.5]), (16,))

In [ ]:
x2 = np.linspace(-4, 4, 16)
x2, x2.shape

(array([-4.    , -3.4667, -2.9333, -2.4   , -1.8667, -1.3333, -0.8   , -0.2667,  0.2667,  0.8   ,
         1.3333,  1.8667,  2.4   ,  2.9333,  3.4667,  4.    ]), (16,))

In [ ]:
rx0 = rx[:,0]
w = np.where(rx0 > 1.5)
w   # w is a tuple, so needs indexed when using

(array([24, 27, 37, 69, 83, 84, 85, 86]),)

In [ ]:
for index in w[0]:
    print(f"{index}: {rx0[index]}")

24: 1.5106615960632106
27: 1.555317376922868
37: 1.5010029032007484
69: 1.9232354210274734
83: 1.5280179050125617
84: 2.3040471945562104
85: 1.984287464813517
86: 1.8938399298863136
